- name: demo on task varibales
  hosts: local
  connection: local
  vars:
      COURSE="ANSIBLE"
  tasks:
    - name: demo on task varibles
      vars:
          COURSE="ANSIBLE IN DEVSECOPS"
      debug:
        msg: "Couse name is {{ COURSE }}"