- name: loops demo
  hosts: local
  connection: local
  tasks:
    - name: demo on loops
      debug:
        msg: "The loop items are {{ item }}"
      loop:
        - 1
        - 2
        - 3
        - 4