- name: demo on error handling
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: check user Exists or not
      command: id roboshop
      register: user_output

    - name: print the output for roboshop user
      debug:
        msg: "{{ user_output }}"